# -*- coding: utf-8 -*-
"""ETL Avon MX Estrutura de Alocação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPm0hxsCaD9pfJt5e7tSOn1AUWtP7d_G
"""

import pandas as pd

url='/content/erro_estrutura_alocacao_avon_mx-1721132905072.csv'

df = pd.read_csv(url)
df

url2=('/content/estruturas_avmx_20240319_185909.csv')

df2 = pd.read_csv(url2)
df2

df.loc[df['person_id'] == '7b187a22-f34d-46fc-822e-1e6f5a794e70']

df2.loc[df2['Nome municipio'].str.contains('^TUXPAN.*') & df2['Nome colonia'].str.contains('^ LOC.*')]